### ISSUE TITLE
debug or compile and flash

### ISSUE THREAD

**Issue by muhammedfurkan** [MuhsinFatih/stm32-Visual-Studio-Code-template#1]
is this only coding from vscode ? 

it would be great if we could use it to run , compile and debug.

[this url](https://hbfsrobotics.com/blog/configuring-vs-code-arm-development-stm32cubemx) (Using Visual Studio Code with STM32CubeMX for ARM Development)

**Comment by MuhsinFatih** [comment]
hi! sorry for the late response. I hacked this workaround quickly and didn't bother to add those. I don't have and stm32 line arm processors with me right now, if you are willing to help, maybe we can add those features. If you ask me though, I think stm32 line is a bunch of poorly maintained badly documented garbage microprocessors. I'd suggest the newer nucleo boards (though they are also stm32 line, but have a lot of differences. See my frustration? STM likes to confuse people)
